name: Build and Release Wheels

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

permissions:
  contents: write # needed to create a GitHub release

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-13 # intel
          - os: macos-14 # apple silicon
          # - os: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_SKIP: "pp* *-musllinux_* cp36-* cp37-* cp38-*"
          CIBW_TEST_COMMAND: 'pip install pytest && pytest {project}/tests -s'

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error
          retention-days: 1

  create_release:
    name: Create GitHub Release
    needs: [build_wheels] # block on build_wheels
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Only run on tag pushes

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true # put all wheels into working dir

      # Optional: show what we're about to upload
      - name: Show files
        run: ls -l

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.whl
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authentication
