name: C++ unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y valgrind
    - name: Run C++ tests
      run: |
        cd tests
        make
        valgrind --leak-check=full ./test_driver
